chore: bumped version in preparation for next release
unitystation/stationhub pull request #135
Opened 2021-11-29 05:54 UTC by corp-0

I will fukken release it, yes I will.

I tested auto updating in my windows machine and it worked flawlessly (I hosted a local API and http file directory).

2021-11-29 09:05 UTC, RedlineTriad requested changes

2021-11-29 09:05 UTC, RedlineTriad commented on UnitystationLauncher/Models/ConfigFile/Config.cs
> +        public const string ValidateUrl = "http://localhost:8000/";
Pretty sure this is wrong

2021-11-29 16:32 UTC, corp-0 commented on UnitystationLauncher/Models/ConfigFile/Config.cs
> +        public const string ValidateUrl = "http://localhost:8000/";
```suggestion
        public const string ValidateUrl = "https://api.unitystation.org/validatehubclient";
```

2021-11-29 23:51 UTC, corp-0 commented on UnitystationLauncher/Models/ConfigFile/Config.cs
> +        public const string ValidateUrl = "http://localhost:8000/";
done

2021-11-29 23:52 UTC, corp-0 commented
https://app.codacy.com/gh/unitystation/stationhub/pullRequest?prid=8481324 codacy passed but never reported back, it seems

2021-11-29 23:53 UTC, corp-0 commented on UnitystationLauncher/Assets/org.unitystation.StationHub.metainfo.xml
> +			<p>Unitystation got a face lifting with some first iterations of future features!.</p>
```suggestion
			<p>StationHub got a face lifting with some first iterations of future features!.</p>
```

2021-12-01 07:40 UTC, RedlineTriad approved these changes, later dismissed

2021-12-01 15:56 UTC, corp-0 commented
I can't merge :(

2021-12-02 21:54 UTC, RedlineTriad commented
You could just squash and force push, that should trigger a status update? maybe?

2021-12-03 01:05 UTC, corp-0 commented
yeah, it is something else. It did the same for the previous commit, I think it simply borked

2021-12-10 23:32 UTC, corp-0 commented
fixed codacy, I'm only missing your green check now!

2021-12-11 11:12 UTC, RedlineTriad approved these changes

2021-12-11 18:33 UTC, merged