Various fixes
unitystation/stationhub pull request #176
Opened 2023-03-03 22:25 UTC by CorruptComputer

Changes:
- Hides the debug console (Fixes #116)
- Adds a way to hide WIP Tabs like the Settings tab (Fixes #164)
- Adds a 'By: <>' field to the changelog
- Adds a Flatpak build to the CI so failures there can be caught in the future
- Adds a link to the Discord and the Launcher issues (Fixes #129)
- Includes some general code cleanup around the areas I was editing

![image](https://user-images.githubusercontent.com/5573038/222840289-c66dec4b-4a23-47ed-b2fa-6ae832a3351e.png)

This has been tested on Linux and in a Windows VM.

2023-03-03 22:43 UTC, CorruptComputer commented on UnitystationLauncher/ViewModels/ChangelogViewModel.cs
>          {
Codacy says to remove this, but this is part of the required method signature by the task scheduler. Even if we aren't using these parameters we have to have them.

2023-03-03 22:45 UTC, CorruptComputer commented on UnitystationLauncher/ViewModels/ChangelogViewModel.cs
>          {
![image](https://user-images.githubusercontent.com/5573038/222845669-28beb6a2-221e-49ce-9602-87e790449cf8.png)

Removing this:
![image](https://user-images.githubusercontent.com/5573038/222845893-ad66ac9b-4a34-428e-93ba-ab82b55b90e5.png)

2023-03-03 23:45 UTC, corp-0 requested changes

2023-03-03 23:45 UTC, corp-0 commented on UnitystationLauncher/ViewModels/ChangelogViewModel.cs
> +        private async Task GetPullRequestsAsync(IScheduler scheduler, CancellationToken cancellationToken)
```suggestion
        private async Task GetPullRequestsAsync(IScheduler _, CancellationToken cancellationToken)
```

this should suffice to comply with the signature and communicate it is an unused parameter

2023-03-03 23:45 UTC, corp-0 commented on UnitystationLauncher/ViewModels/ChangelogViewModel.cs
> +        ObservableCollection<PullRequestViewModel> PullRequests { get; }
```suggestion
        private ObservableCollection<PullRequestViewModel> PullRequests { get; }
```

I understand this didn't have it before, but please prefer to use explicit access modifier.

2023-03-03 23:45 UTC, corp-0 commented on UnitystationLauncher/Program.cs
> +                                                                                                     //.With(new Win32PlatformOptions {  }) // Windows Specific
what's up with the commented out code?

2023-03-03 23:48 UTC, CorruptComputer commented on UnitystationLauncher/Program.cs
> +                                                                                                     //.With(new Win32PlatformOptions {  }) // Windows Specific
I had commented these out while testing and forgot to remove them. Will fix that.

2023-03-03 23:56 UTC, corp-0 submitted a review, later dismissed

2023-03-03 23:56 UTC, CorruptComputer commented on UnitystationLauncher/Program.cs
> +                                                                                                     //.With(new Win32PlatformOptions {  }) // Windows Specific
Should be fixed now, I also updated the comments to explain a bit better. They were slightly misleading before, as those were just my guesses as to what they were. I checked the Avalonia source code for them now, so these should be correct.

2023-03-03 23:57 UTC, CorruptComputer commented on UnitystationLauncher/ViewModels/ChangelogViewModel.cs
> +        ObservableCollection<PullRequestViewModel> PullRequests { get; }
No worries, please do tell me about these if you see them. Getting the code to be more standardized is always good.

2023-03-03 23:57 UTC, CorruptComputer commented on UnitystationLauncher/ViewModels/ChangelogViewModel.cs
> +        private async Task GetPullRequestsAsync(IScheduler scheduler, CancellationToken cancellationToken)
Ah yeah thanks, should be fixed now.

2023-03-04 00:01 UTC, corp-0 commented
seems like codacy is eating glue, can you push an empty commit to force it run again?

2023-03-04 00:09 UTC, corp-0 commented
I dismissed that codacy issue, can you trigger ci again, please?

2023-03-04 00:15 UTC, corp-0 approved these changes

2023-03-04 00:15 UTC, merged